# Generated by Django 4.2.3 on 2023-08-03 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_logimail'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Активен'), (False, 'Заблокирован')], default=True, verbose_name='Статус пользователя'),
        ),
    ]
