# Generated by Django 4.2.3 on 2023-08-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mailing_mailing_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('block_user', 'Block or unblock client')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('stop_mailing', 'Stop or run mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
